### ISSUE TITLE
"Window not found" (linux)

### ISSUE THREAD

**Issue by twoheadedlamb** [KevAquila/WEBFISHING-Guitar-Player#12]
the reason is very likely because i am using linux (debian 12) and running the program via Wine, but the program boots fine.
When hitting the play button on the song it states "Failed to find target window" in an Wine error message.
![2024-10-27_14-44](https://github.com/user-attachments/assets/98f4e0de-2dc4-4f50-a383-de9a7a8daaf0)

**Comment by lyricalpaws** [comment]
+1

**Comment by KevAquila** [comment]
Could try running the game in wine also.  This was designed for windows.  I should have made that a bit more apparent.

**Comment by Velkee** [comment]
The game doesn't have a native Linux build, so the game will most likely be running under Wine (or Steam's variation, Proton). I'll try to run the player under the same prefix as the game and report back if that works

**Comment by Velkee** [comment]
That doesn't seem to work either, can't find the songs folder when I try. I don't know the specifics of how this program works, but if it just sends keyboard signals to play then making it Linux-compatible should be possible

**Comment by rayzr522** [comment]
got it working with protontricks personally. here's what i did:

1. install pipx (im on pop os so it was just `sudo apt install pipx`)
2. install protontricks (`pipx install protontricks`)
3. download guitar player from releases
4. unzip
5. cd into the `GuitarPlayer` folder
6. run `protontricks-launch --appid 3146520 ./MIDIProcessor.exe` for the midi processor
7. run `protontricks-launch --appid 3146520 ./Guitar\ Player\ v1.1.0.exe` for the player

works just fine for me! hope it works for you

**Comment by twoheadedlamb** [comment]
> got it working with protontricks personally. here's what i did:
> 
>     1. install pipx (im on pop os so it was just `sudo apt install pipx`)
> 
>     2. install protontricks (`pipx install protontricks`)
> 
>     3. download guitar player from releases
> 
>     4. unzip
> 
>     5. cd into the `GuitarPlayer` folder
> 
>     6. run `protontricks-launch --appid 3146520 ./MIDIProcessor.exe` for the midi processor
> 
>     7. run `protontricks-launch --appid 3146520 ./Guitar\ Player\ v1.1.0.exe` for the player
> 
> 
> works just fine for me! hope it works for you

hey it seems to work?? music is playing... just not good... im using the preloaded songs so idk. im gonna try it with some songs i load in myself maybe and see if that helps

**Comment by twoheadedlamb** [comment]
> > got it working with protontricks personally. here's what i did:
> > ```
> > 1. install pipx (im on pop os so it was just `sudo apt install pipx`)
> > 
> > 2. install protontricks (`pipx install protontricks`)
> > 
> > 3. download guitar player from releases
> > 
> > 4. unzip
> > 
> > 5. cd into the `GuitarPlayer` folder
> > 
> > 6. run `protontricks-launch --appid 3146520 ./MIDIProcessor.exe` for the midi processor
> > 
> > 7. run `protontricks-launch --appid 3146520 ./Guitar\ Player\ v1.1.0.exe` for the player
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > works just fine for me! hope it works for you
> 
> hey it seems to work?? music is playing... just not good... im using the preloaded songs so idk. im gonna try it with some songs i load in myself maybe and see if that helps

nope it still sounds bad :P

**Comment by rayzr522** [comment]
well it can only do so much, if it's playing then it's probably playing as well as it can (regardless of Wine). but re: the original issue of it not recognizing the window, maybe it would be worth including the instructions I provided in the readme. if nobody else makes a PR I'll probably do so next time I am at my PC and remember ^^

**Comment by sealldeveloper** [comment]
Gday

I'm running into this issue again with the `protontricks-launch` lines from the README.

I am using a Flatpak installation of Steam, which might be having some issues with sandboxing.

**Edit:** I have also tried with Steam installed normally via rpmfusion, it also does not work. I am on Fedora 40.

**Comment by foxfirecodes** [comment]
did you install protontricks via pipx, flatpak, or something else? 

if pipx + using a system steam installation didn't work, I'm not sure

if flatpak, you may need to check the protontricks readme for instructions on how to grant filesystem access to your steam library 

if something else like your system package manager, you may need to confirm that it's actually the latest protontricks version. I originally installed protontricks via apt on Pop!_OS, only to realize it was like 5 versions out of date and broken hence why I ended up doing pipx instead

**Comment by sealldeveloper** [comment]
I have tried:
- pipx and system (via rpmfusion from the GNOME Software application)
- pipx and flatpak, I haven't checked the protontricks README though

I did not install protontricks via dnf at all, so I do not think its outdated protontricks.

**Edit:** It seems protontricks has its own Flatpak for Flatpak purposes, I will let you know how that goes.

**Edit 2:** Same error occurs with the Flatpak installation, I installed it with these steps:
```bash
$ flatpak install flathub com.github.Matoking.protontricks
$ echo "alias protontricks='flatpak run com.github.Matoking.protontricks'" >> ~/.zshrc
$ echo "alias protontricks-launch='flatpak run --command=protontricks-launch com.github.Matoking.protontricks'" >> ~/.zshrc
$ source ~/.zshrc
```

I then executed the program:
```bash
$ protontricks-launch --appid 3146520  Guitar\ Player\ V1.1.3.exe
```

Same error

![image](https://github.com/user-attachments/assets/3ac4cac9-6bcd-418a-8de6-945c6793ad07)

Wine Output:
```
steam-runtime-launcher-service[93]: W: The --socket option is deprecated. Prefer to use --session or --bus-name.
steam-runtime-launch-client[95]: W: The --socket option is deprecated. Prefer to use the session bus.
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
wine: using kernel write watches, use_kernel_writewatch 1.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
00e0:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e0:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e0:err:xrandr:xrandr14_get_adapters Failed to get adapters
00e0:err:xrandr:xrandr14_get_adapters Failed to get adapters
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
011c:fixme:oleacc:find_class_data unhandled window class: L"#32769"
011c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
011c:fixme:uiautomation:default_uia_provider_callback Default ProviderType_NonClientArea provider unimplemented.
00d8:fixme:uxtheme:SetPreferredAppMode 2: stub
011c:fixme:oleacc:find_class_data unhandled window class: L"#32769"
011c:fixme:uiautomation:base_hwnd_fragment_get_FragmentRoot 0000000001359F78, 000000000021F9D0: stub!
011c:fixme:uiautomation:base_hwnd_fragment_GetEmbeddedFragmentRoots 0000000001359F78, 000000000021F9E0: stub!
00d8:fixme:msg:ChangeWindowMessageFilter c047 00000001
00d8:fixme:msg:ChangeWindowMessageFilter 111 00000001
00d8:fixme:dwmapi:DwmSetWindowAttribute (0000000000010066, 14, 000000000011FE50, 4) stub
0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000139C140, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000135CAD0, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000139BB50, 10002, 0000000001A3F8A0: stub
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000139C140, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000135CAD0, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000139BB50, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000139C140, 10002, 0000000001A3F8A0: stub
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000135CAD0, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"ListBox"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000139BB50, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"ListBox"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000139C140, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"Button"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000139BB50, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"Button"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000135E360, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"Button"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000135CAD0, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"Button"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000139BB50, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"Button"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000135E360, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"Button"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000135CAD0, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"#32770"
0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000135E360, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0128:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
0128:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 000000000135CAD0, 10002, 0000000001A3F8A0: stub
0128:fixme:oleacc:find_class_data unhandled window class: L"#32769"
```

**Comment by yobson1** [comment]
[my player](https://github.com/yobson1/webfishing-midi) has native linux support, u can just use that if you'd like @sealldeveloper

**Comment by sealldeveloper** [comment]
> [my player](https://github.com/yobson1/webfishing-midi) has native linux support, u can just use that if you'd like @sealldeveloper

Did use I just prefer the UI this provides, it seems to work but not with different resolutions (similar to this one).

Had to compile for myself on Fedora but it *should* work on 1920x1080 when I do a resize.

**Comment by sealldeveloper** [comment]
Update, this seems to have its own host of issues such as double playing notes, and other problems. It does function but not nearly as well as this project.

I will make an issue there for now.

**Comment by foxfirecodes** [comment]
@sealldeveloper id rather not put this burden on the repo owner as I was the one who added the Linux instructions. I recently got this working again on a fresh Arch install, and id be curious to debug why it's not working for you... if you'd like to try and debug it together my discord is foxfirexo!

**Comment by sealldeveloper** [comment]
> @sealldeveloper id rather not put this burden on the repo owner as I was the one who added the Linux instructions. I recently got this working again on a fresh Arch install, and id be curious to debug why it's not working for you... if you'd like to try and debug it together my discord is foxfirexo!

Happy to do, sent a friend request.

**Comment by george2781** [comment]
I believe that unless sealldeveloper and foxfirecodes found a solution this issue needs to be reopened, the instructions in the readme don't seem to work on steam deck's linux
