### ISSUE TITLE
Reader considers certain files as stop points

### ISSUE THREAD

**Issue by QueenOfRodents** [KevAquila/WEBFISHING-Guitar-Player#13]
I'm not entirely sure whether it is due to an unoptimized file, but I have noted that MIDI Processor would specifically treat a certain file of mine as a "stop" rather than converting it or past it. Specifically, whenever I would try to convert one of my midis in particular, it would not convert it, and would actually consider it a break point. No files placed after it would be converted, and if put as the only file/top of the file, nothing would be generated. I have tested it and have realized it is specifically this file, no others caused it.

I do have the link to the file in question, and I am not experienced at all with editing MIDIs, but I would like to know what causes this. The link to the file is: https://songs.bardmusicplayer.com/?dl=1153668247397343353. If this is an issue that is easily fixed or has been asked before, I apologize.

Thank you for your time.

**Comment by zephiowl** [comment]
Heyaaaaa, so it was just a mild incompatibility with the way the midi was created as far as i was able to tell, i had encountered the same bug you did. 

Tweaked it a _tiny_ amount in fl studio (how you create and edit midi files) and re-exported it to an amazing success~! I've gone ahead and attached the updated midi, and converted files for you here, if that's everything feel free to mark the issue as closed and hopefully it helps!

(btw, you dont need to convert them anymore but just thought i'd do it to help you out)
[(Ayla Storm) Scatman - Scatmans World.zip](https://github.com/user-attachments/files/17784585/Ayla.Storm.Scatman.-.Scatmans.World.zip)

**Comment by QueenOfRodents** [comment]
Hell yeah, you're the best! Thank you so much.
