### ISSUE TITLE
cant find exe file

### ISSUE THREAD

**Issue by LioGamer7o6** [KevAquila/WEBFISHING-Guitar-Player#14]
I downloaded the zip but when I go into the guitar player there are no exe files
![image](https://github.com/user-attachments/assets/ea81fcc1-fb5d-42cb-b5af-737ac262e9f1)

**Comment by KevAquila** [comment]
Looks like you downloaded the source code.

https://github.com/KevAquila/WEBFISHING-Guitar-Player/releases

Download the GuitarPlayer.zip from here for a pre-compiled .exe
