### ISSUE TITLE
Doesn't seem to work for me at all

### ISSUE THREAD

**Issue by Nyapano** [KevAquila/WEBFISHING-Guitar-Player#2]
I loaded up the game, pulled out a guitar, and tried running a song (i went through nearly all of them) and the notes just seem totally random. These are the songs that came pre-packaged, I'm unsure if I've done something wrong, some setup that wasn't mentioned or I missed, but I can't seem to get it working

**Comment by Nyapano** [comment]
https://github.com/user-attachments/assets/88ce26a2-f0e6-4d7f-8f57-67d6cc751c6b


https://github.com/user-attachments/assets/7c5fe771-657d-490d-8cb7-5b577f9371af


https://github.com/user-attachments/assets/41712f7b-8f67-4a85-9d68-cb7e3cb6fdf8

I recorded three short videos for demonstration

**Comment by KevAquila** [comment]
What is your game resolution?  The only thing I could think is that the resolution and positioning of the guitar fret board is off.

**Comment by Nyapano** [comment]
1920x1080, I'll try again with some diff resolutions

**Comment by Nyapano** [comment]
This seems to be the problem, it worked fine at 1360x768, other resolutions all seemed a little off.
Even still, at that resolution it was skipping occasional notes, but worked way better than it previously did

**Comment by KevAquila** [comment]
Try not having your mouse on the window, I haven't done extensive testing, but I try to keep Webfishing in the background while it plays.  I've noticed that moving the mouse around in the game can cause it to "miss" input from the player.

**Comment by Nyapano** [comment]
That seemed to have it repeat the same single note, I wonder if there's something wrong with my laptop to keep this from working

**Comment by KevAquila** [comment]
The only other thing I see off would be the lack of a title bar for your window, not too sure what you have going on there.

**Comment by Nyapano** [comment]
Those recordings were taken in  full-screen mode, but I had the same results in windowed

**Comment by dwang733** [comment]
I ran into the same issue. I found that setting the resolution to 1360x768, windowed mode, and resizeable window disabled worked for me.

**Comment by KevAquila** [comment]
I've also heard that running it as an Administrator can help with it.

**Comment by KevAquila** [comment]
Added some more checks in the v1.1.0, hopefully it should play better now.
