### ISSUE TITLE
Monkeys designed Github?

### ISSUE THREAD

**Issue by Ihatethewebsiteimon** [KevAquila/WEBFISHING-Guitar-Player#22]
This website was made by spider monkeys?

**Comment by pixl-strite** [comment]
did you install "Source code (.zip)" or "GuitarPlayerV1.1.1.zip"?

**Comment by Ihatethewebsiteimon** [comment]
> did you install "Source code (.zip)" or "GuitarPlayerV1.1.1.zip"?
The zip I have is called "WEBFISHING-Guitar-Player-main.zip"
