### ISSUE TITLE
Exe's Not there / Wont Launch

### ISSUE THREAD

**Issue by Wintoli** [KevAquila/WEBFISHING-Guitar-Player#4]
Hey I may just be stupid, but when trying to launch either program, they just launch projects in Visual Studio Code, trying to build / run, it says it succeeded, but no midis are actually created. Any help is appreciated

**Comment by KevAquila** [comment]
It sounds like you might have downloaded the source code instead of the GuitarPlayer.zip from the Releases page.

**Comment by Wintoli** [comment]
God I'm stupid, sorry been a hot sec since using Github. Appreciate it.
