### ISSUE TITLE
Playback speed ajustment

### ISSUE THREAD

**Issue by Crossunite** [KevAquila/WEBFISHING-Guitar-Player#5]
Firstly, thank you for making something like this! I was wondering how long it would take.
I think it would be useful to be able to control the playback speed of the midis; sometimes the player trips over itself if theres too much happening in a song at once. Being able to adjust it could potentially ease the burden on the player when it needs to swap notes frequently, or just make it a more relaxing vibe to match the pace of the game.
/

**Comment by KevAquila** [comment]
This would be great to have, even a pause button and a progress status would be nice.  I would have to swap from WINAPI to a better GUI framework.  It's something I can work on.

**Comment by KevAquila** [comment]
This was just added in v1.1.0
