### ISSUE TITLE
Notes are jumbled and wrong

### ISSUE THREAD

**Issue by ghost** [KevAquila/WEBFISHING-Guitar-Player#6]
Playing any of the songs just made a garbled mess out of the notes, and no amount of troubleshooting seemed to do anything about it. I was told it was intended to be used on 1920x1080 fullscreen resolution, but tinkering with that had no results.

I went to the provided discord to seek support, but they weren't able to help.
The person helping me didn't respond for 10 minutes at one point, and then responded to my wondering where they went by explaining that it was because he was working, which I understood and was fine with. I mention this because it then ended with other members of the discord attacking me because they perceived me as being impatient and demanding. Those people mean nothing to me so I'm not bothered, but I certainly won't be using the discord server again.

This is just to submit that there's an issue that prevented the program from working properly. Don't comment on this post. Thank you, and good luck with the program. Happy fishing!

**Comment by KevAquila** [comment]
You deleted your messages from the discord server.  I was not there at the time, but I strongly get the feeling that you know you were in the wrong.
