### ISSUE TITLE
unable to launch

### ISSUE THREAD

**Issue by juiceyfruits** [KevAquila/WEBFISHING-Guitar-Player#7]
I'm not sure what I did wrong, but when I try to launch the player I get an error message that reads "The code execution cannot proceed because VCRUNTIME140_!.dll was not found. Reinstalling the program may fix this problem."
But I've reinstalled a few times and I'm still receiving the error. Any insight?

**Comment by KevAquila** [comment]
Sounds like you need the redistributables from Microsoft.

https://aka.ms/vs/17/release/vc_redist.x64.exe
