### ISSUE TITLE
Error trying to open the exe

### ISSUE THREAD

**Issue by PedroPedrassolli** [KevAquila/WEBFISHING-Guitar-Player#8]
![image](https://github.com/user-attachments/assets/000771c9-3eb9-4eaf-8fa5-55a2c9c2e406)

**Comment by PedroPedrassolli** [comment]
This starts happening once i convert some MIDI files

**Comment by miklovinn** [comment]
I am also getting this same issue after downloading v1.1.1

**Comment by BoxOfSquid** [comment]
Check the names of your MIDI files for Korean or Japanese characters. You'll need to remove them from the file name.

**Comment by KazuyukiKasuke** [comment]
checked my files for korean and jp characters and removed them all, but no luck either. I've redownloaded the files a few time and I'm also having this error pop up constantly

**Comment by KevAquila** [comment]
Should be fixed in the latest version.
